services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tele_chatbot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env:ro

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run celery -A src.celery_app worker --loglevel=info
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run celery -A src.celery_app beat --loglevel=info
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres_data:
