"""add reminder_minutes

Revision ID: 99ababbb28e0
Revises: 87ae9f4e6add
Create Date: 2026-03-10 19:24:03.278442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ababbb28e0'
down_revision: Union[str, Sequence[str], None] = '87ae9f4e6add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('reminder_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'reminder_minutes')
    # ### end Alembic commands ###
